### ISSUE TITLE
Initial State

### ISSUE THREAD

**Issue by mp1pro** [ChrisD1221/bwa-u3-jammming-prj#4]
The correct way to set the initial state within the constructor is like so

```
    this.state = {
      searchResults: [],
      playlistName: 'New Playlist',
      playlistTracks: []
};
```

**Comment by ChrisD1221** [comment]
So Nothing inside the Arrays?

**Comment by mp1pro** [comment]
Not really, you have
`this.state.searchResults = {....`
it should be
`this.state= {....`

For further help, contact a react adviser at http://codecademy.com
